/MTX
;
; Mensajes del juego.
;
/0
Pod‚is salir de la celda para ir al laboratorio.
/1
Pod‚is salir del laboratorio para volver a la celda.
/2
Una bonita l mpara de lat¢n. ¨Os pregunt is para qu‚ querr  el brujo un objeto tan vulgar?
/3
Est  tallada en el muro de la torre, no tiene barrotes ni postigos. A trav‚s de ella pod‚is ver un desierto que parece infinito.
/4
Las paredes son de piedra maciza. 
/5
Palp is cuidadosamente los grandes bloques de piedra en busca de alg£n indicio que os ayude a escapar... ­En uno de ellos descubr¡s lo que parece un relieve! 
/6
Est  en su cuarto creciente por lo que proyecta una luz d‚bil a trav‚s de la ventana.
/7
La noche est  estrellada, y titilan, azules, los astros, a lo lejos...
/8
Est  cerrada.
/9
La figura est  firmemente sujeta a la pared y no cede.
/10
Los l¡neas de piedra que forman el hexagrama est n talladas en la roca y no pueden ser presionadas.
/11
No tiene puerta ni postigos.
/12
Pesa demasiado.
/13
¨Qui‚n sabe qu‚ ominosas fuerzas podr¡a desatar la magia contenida en estos frasquitos? La prudente Viviana os ense¤¢ que nunca se deben manipular objetos m gicos cuyo poder desconozcamos.
;
; El mensaje 14 se usa por Triz2DAAD como texto de introducci¢n del juego.
;
/14
En los viejos buenos tiempos, cuando el Rey Arturo gobernaba sobre la querida tierra de Logres, hab¡a caballeros andantes que eran valientes y esforzados y tambi‚n doncellas bell¡simas y muy prudentes que aprend¡an la ciencia de las hadas y viv¡an en la islade Aval¢n junto al mago Merl¡n y la Dama del Lago.

/15
/16
/17
/18
 INSTRUCCIONES.

/19
El ordenador te dar  una breve descripci¢n del lugar donde te encuentras. T£ debes escribir ¢rdenes utilizando un verbo en infinitivo, acompa¤ado de un sustantivo. Por ejemplo "abrir ventana". Tambi‚n puedes construir ¢rdenes m s complejas como "golpear 
/20
al otro un gran espejo con marco de rub¡. En el centro hay una gran mesa llena de frasquitos de diversas formas y colores. No parece haber m s salidas que el pasillo de regreso a la celda.
/21
un gran colch¢n de plumas. Una recia puerta de madera separa la celda del laboratorio del brujo.
/22
Entre ellas destacaba por su buen juicio y gentil hermosura una joven castellana, hija de un pr¡ncipe de la peque¤a Breta¤a. Era conocida por todos como do¤a Elisa de Aval¢n. 

/23
Un d¡a do¤a Elisa se encontraba solaz ndose en la floresta de Brocelianda, cuando un horrible nigromante venido de oriente la secuestr¢ y se la llev¢ muy lejos, a tierra de infieles. Nada m s llegar a su torre de alta hechicer¡a el brujo orden¢ vestirla de 
/24
Encerrada en una fr¡a celda sab‚is que os queda muy poco tiempo antes de que regrese el brujo.... A miles de jornadas de Aval¢n, en lo alto de una torre en medio de un desierto que parece infinito, sin la ayuda de Merl¡n y Viviana, privada del poder de 
/25
odalisca y ahora se acicala para disfrutar de su bot¡n y cometer todo tipo de tropel¡as con el cuerpo de diosa de la inocente Elisa...

/26

De pronto las luces del candelabro se apagan. El
/27
A trav‚s de la ventana la p lida luz de la noche parece brillar con resplandores surgidos del mism¡simo infierno. Espantada, sin saber qu‚ hacer, os acurruc is en un rinc¢n de la celda.
/28
 aire se vuelve pesado, y una presencia ominosa lo inunda todo. 
/29
/30
 Vuestro coraz¢n late con tanta intensidad que apenas os deja escuchar el sonido de los pasos que se acercan por el pasillo. La puerta se abre de golpe y el brujo, con una sonrisa retorcida, entra en la estancia. Sab‚is que vuestra £ltima oportunidad se ha 
/31
desvanecido. Su mirada lasciva os envuelve como una oscura serpiente... sent¡s sus repugnantes manos acariciar con deseo vuestra delicada piel y despu‚s... todo se vuelve gritos, horror y tinieblas....


   FIN

/32

De pronto el
/33
El cristal de la ventana, con su extra¤a geometr¡a no euclidiana, deja de mostrar el desierto y la noche y comienza a brillar con resplandores que parecen surgir del mism¡simo infierno. Espantada, sin saber qu‚ hacer, corr‚is hacia la celda y trat is de 
/34
cerrar la puerta.
/35
Est  hecha en madera de roble y adornada con remaches de hierro. No tiene picaporte ni aldaba. 
/36
Imponente. Se sustenta en una pesada base de oro macizo. Una vela arde en cada uno de sus brazos sin consumirse.
/37
Las velas deben haber sido creadas por alg£n sortilegio pues cuando intent is tocarlas o quemar algo en ellas es como si no existieran.
/38
Parece que hay algo escrito en ‚l, pero con tan poca luz es imposible leerlo.
/39
A la luz de las velas pod‚is leer sin dificultad el texto del pergamino.

­Loado sea Jesucristo y su Sant¡sima Madre... Est  en lat¡n!

Se trata de una conjuro para encantar alfombras voladoras. Dice as¡: 


"Nocte serena, super capeto sedente, dicendumst palyndromon hoc:

'IN GIRUM IMUS NOCTE ET CONSUMIMUR IGNI'.

Statim ut avis evolabit vestis, domino suo parente."


Lo que en vuestro materno dialecto bret¢n viene a querer decir que para encantar una alfombra y que os lleve volando donde quer is hay que sentarse sobre ella y pronunciar la palabras m gicas del verso antedicho.
/40
Hay algo extra¤o en su geometr¡a no euclidiana... ominoso.
/41
Parece infinito...
/42
Frot is la l mpara, pero no sucede nada... ¨Acaso esperabais ver aparecer a un yinn dispuesto a concederos tres deseos? ­Ese es otro cuento, mi hermosa castellana!
/43
Al examinar con atenci¢n el trozo de tela en seguida os dais cuenta de que se trata de un pergamino.
/44
Est  compuesta por decenas de c¢dices  rabes, griegos, persas, indios, chinos y hebreos... 
/45
Por desgracia sin vuestros poderes m gicos sois incapaz de entender ninguna de estas lenguas... tan solo record is las dos que aprendisteis en el castillo de vuestros padres antes de conocer a Merl¡n y Viviana: el lat¡n y el bret¢n armoricano.
/46
Representa una estrella de David en cuyo interior hay incrustado alg£n tipo de figura regordeta.
/47
Palp is con atenci¢n la figura. Parece hecha de marfil o de alg£n material similar y, por la forma, dir¡ais que es un elefante.
/48
Al presionar la figura un mecanismo de cadenas y poleas se pone en marcha en el interior de los muros hasta terminar con un chasquido sordo procedente de la puerta de la celda. Ahora la puerta de la celda est  abierta.
/49
­Ya lo hab‚is hecho!
/50
La puerta se mantiene firmemente cerrada y no cede a vuestros embates.
/51
Ahora la puerta est  abierta. Conduce a un largo pasillo al final del cual pod‚is ver un resplandor procedente del laboratorio del brujo.
/52
A£n no hab‚is estado en ning£n sitio al que pod is "volver"...
;/53
;Comprob is que la l mpara carece de aceite y, por tanto, de utilidad alguna.
/53
Intent is encender la l mpara, pero al inspeccionarla con m s detenimiento os dais cuenta de que est  vac¡a; ni rastro de aceite ni de mecha en su interior.
/54
No pod‚is evitar experimentar un sentimiento de complacencia al ver vuestra imagen en el espejo: las finas sedas color esmeralda y las sensuales joyas orientales realzan de manera extraordinaria vuestro imponente cuerpo de diosa celta de cabellos leonados, 
/55
ojos azules y piel blanca y suave como la pluma de un  ngel. Sin embargo pronto la natural vanidad femenina es sustituida por el espanto de recordar a qu‚ repugnante barrag n le est  destinado beber el vino de tan dulce c liz.
/56
candado con la barra". Algunos comandos £tiles son: "mirar" o "m", que te repite la descripci¢n del lugar donde te encuentras; "examinar" o "ex" para que el ordenador te describa alg£n detalle espec¡fico del lugar donde est s o de los objetos que encuentres; "coger" y "dejar", "inventario" o "i" para ver los objetos que llevas, "esperar" para hacer pasar el tiempo en el juego, y "salidas" o "x" para ver las salidas de la localidad en la que te encuentras. 


En esta aventura tienes un n£mero de acciones limitado antes de que el nigromante regrese. No sabes cu ntas son, lo cual a¤ade una tensi¢n mayor al juego.

/57
Est  firmemente sujeto a una base de oro macizo que parece inamovible.
/58
Durante un instante os sent¡s tentada a arrojaros al vac¡o para evitar la deshonra de ser mancillada por el nigromante...
/59
 en el £ltimo momento record is las sabias palabras que siempre repite Merl¡n a las hadas de Aval¢n: "Hijas m¡as... Nunca perd is la esperanza... Cuando el miedo os atenace... ­Apostad siempre por la vida!"
;/60
;El cristal tiene una robustez que resiste cualquier embate.
/60
La ventana parece resistir cualquier intento de da¤o, como si estuviera protegida por un sortilegio poderoso o, quiz s, por la misma geometr¡a incomprensible de su estructura.
/61
Ante vuestro ¡mpetu el espejo estalla en un fracaso de cristales. 
/62
El cristal es impenetrable...
/63
Ahora el marco de rub¡ est  hueco y el suelo lleno de pedazos de espejo rotos.
/64
Un largo pasillo que conduce a la celda.
/65
Ahora ten‚is un pedazo de espejo roto... Pero dejadme que os diga algo, mi se¤ora do¤a Elisa: es un red herring m s in£til que el codo de un playmobil.
/66
Ya hab‚is cogido un trozo de espejo antes, no necesit is m s...
/67
Cortantes trozos de espejo esparcidos por el suelo...
/68
Un resto afilado de lo que anta¤o fuera un ostentoso espejo. Lo contempl is mientras la mirada se os desv¡a involuntariamente hacia la p lida piel de vuestras mu¤ecas. Turbias ideas os asaltan el pensamiento...
/69
Por un aterrador segundo os tienta la idea de escapar de vuestro destino dejando tan solo un cuerpo inerte en manos del oscuro hechicero...
/70
­No ten‚is con qu‚ cometer tan dr stica acci¢n!
/71
vuestros sortilegios... ¨C¢mo lograr‚is escapar?

/72
A pesar de acercar el pergamino a la ventana y examinarlo bajo la tenue luz de la luna, segu¡s sin poder descifrar lo escrito: la oscuridad en la celda sigue siendo demasiado densa para leerlo.
/73
Observ is el 
/74
 Trozos de espejo roto yacen esparcidos alrededor del ahora vac¡o marco de rub¡.
/75
Pos is delicadamente vuestros finos dedos sobre la fr¡a superficie del espejo. Su reflejo permanece impasible, devolvi‚ndoos vuestra seductora imagen.
/76
Con un fulgor escarlata abraza el espejo como un uroboro de fuego.
/77
Ahora el marco de rub¡ est  vac¡o. Tras el solo hay una pared sin ning£n inter‚s.
/78
 con detenimiento, recorriendo cada rinc¢n de piedra fr¡a y desnuda, pero no hall is nada fuera de lo com£n. Solo el eco de vuestra respiraci¢n acompa¤a el silencio de
/79
suelo
/80
techo
/81
No es necesario, ya hay suficiente luz aqu¡ para leerlo con claridad.
/82
Empuj is 
/83
la pesada mesa 
/84
cambiando levemente su posici¢n
/85
 mientras el sonido de los frascos chocando unos con otros por el movimiento llena la estancia
/86
, pero vuestra acci¢n no revela nada de inter‚s.
/87
con esfuerzo el pesado espejo 
/88
con facilidad el ahora vac¡o marco 
/89
No sent¡s nada extra¤o al tacto.
/90
­No lleg is!
/91
Quiz  bebiendo del seguramente letal contenido de los frascos...

Quiz  usando un trozo del espejo para derramar la sangre de vuestras venas...
/92
Quiz  saltando al vac¡o por el hueco de la ventana...
/93
En vuestra deseperaci¢n lleg is a pensar en poner fin a vuestra vida y, con ella, a vuestra condena pero... ¨c¢mo lo har¡ais?
/94
El contenido de los frascos ser  con toda seguridad venenoso. 
/95
Del espejo ya solo quedan trozos dispersos por el suelo.
/96
Demasiado grande para llevarlo a cuestas.
/97
Sent¡s el impulso de descargar vuestra rabia estrellando los frascos contra el suelo de piedra, pero al final comprend‚is que no servir¡a de nada.
/98
 Y ya hay suficientes trozos de cristal esparcidos por el suelo.
/99
La sangre que corre por vuestras reales venas resalta sobre la palidez de la piel de vuestras mu¤ecas.
/100
Toc is vuestras mu¤ecas, sintiendo el desbocado latir del coraz¢n. Deb‚is relajaros y pensar.
/101
Ser¡a, pens is, algo enteramente futil.
/102
Por un momento ca‚is bajo la presi¢n y ced‚is al llanto desconsolado. Pronto os recompon‚is.
/103
 Debe de haber una forma de escapar.
/104
Lanz is con desesperaci¢n un grito de socorro, con la d‚bil esperanza de que alguien os ayude, pero solo el eco de vuestra propia voz en las p‚treas paredes os responde.
/105
 Quiz  quitaros la vida y abandonar el mundo por vuestra propia mano sea mejor que el destino que os aguarda en manos del nigromante.
/106
Intent is quemar _ con la llama de las velas, pero... 
/107
Sopl is con energ¡a hacia las velas, pero las llamas revelan su naturaleza m gica neg ndose a desaparecer.
/108
Se trata de un delicado lecho de plumas bordado con tela p£rpura. 
/109
Est  colocado sobre una rica alfombra persa. 
/110
Un escalofr¡o de espanto os recorre al pensar qu‚ uso pretende darle el nigromante con vos si antes no logr is escapar.
/111
Empuj is el colch¢n hacia un rinc¢n de la celda. Ahora la alfombra ha quedado descubierta.
/112
Su tacto es muy suave.
/113
No alcanz is a verla bien en la penumbra 
/114
 Por lo que permite ver la luz de la luna, est  finamente tejida y decorada con motivos florales.
/115
Es demasiado grande para que os la pod is llevar.
/116
No pod‚is cogerla bien 
/117
ya que la mayor parte de ella est  bajo el colch¢n.
/118
No pod‚is moverla bien 
/119
Empuj is la alfombra hacia el otro rinc¢n de la celda.
/120
Trat is de relajaros y pensar... 
/121
La alfombra est  
/122
extendida en medio
/123
medio enrollada, apartada en un rinc¢n
/124
 de la celda.
/125
El conjuro requiere que la alfombra est‚ debidamente extendida en toda su amplitud sobre el suelo.
/126
Primero deb‚is volver a extenderla en el suelo.
/127
La alfombra comienza a levitar lentamente y... ­antes de que pod is reaccionar, sale disparada por la ventana! De inmediato sent¡s que los labios se os secan, el est¢mago se retuerce en un nudo de nervios, y una opresi¢n oscura nubla vuestra vista. 
/128
La alfombra comienza a levitar y sale sin ninguna dificultad por la gran ventana de la  celda volando hacia el occidente... en poco tiempo dej is atr s las fr¡as arenas del desierto y antes de lo que nunca hubierais imaginado divis is las amables campi¤as de Galia, los queridos bosques de Breta¤a y por fin... la brumosa Isla de Aval¢n.


­Enhorabuena, do¤a Elisa hab‚is escapado la torre del brujo y hab‚is salvado vuestro precioso cuerpo de ser mancillado por el repugnante nigromante! 


   FINIS CORONAT OPVS

/129
Por m s que intent is recordar alguno de los hechizos que Merl¡n y Viviana os ense¤aron en Aval¢n las palabras no acuden a vuestra mente. Parece que el nigromante os hubiera nublado la raz¢n.
/130
La celda se envuelve en sombras m s densas, como si fueran el s¡mbolo inevitable del fin de vuestra £ltima esperanza de escapar.
/131
Os sent is sobre la alfombra.
/132
Para sentaros apropiadamente en la alfombra ‚sta debe estar extendida sobre el suelo.
/133
En vuestro estado de nervios no pod‚is permanecer quieta en un mismo sitio. Os levant is 
/134
¨A qu‚ alfombra os refer¡s?
/135
Recit is el conjuro que hab‚is memorizado... sin ning£n efecto.
/136
Est is en tal estado de tensi¢n que ni vos misma entend‚is lo que acab is de decir.
/137
/138
 AYUDA POR LOS DA¥OS DE LA DANA EN VALENCIA


Do¤a Elisa de Aval¢n se termin¢ de escribir a finales de Octubre de 2024, coincidiendo con las desastrosas inundaci¢nes que asolaron el sur y el levante de Espa¤a causando numerosas p‚rdidas materiales y humanas.


Nuestros mayores  nimos para todos las personas afectadas.


El pasado 9 de noviembre la asociaci¢n RetroParla (www.retroparla.com) organiz¢ un evento solidario para recaudar fondos destinados a C ritas Valencia. Se pueden hacer aportaciones directamente a ‚sta en el Bizum 38026.


   GRACIAS Y UN ABRAZO A TODAS Y TODOS.

/139
 DO¥A ELISA DE AVALON
/140
Gran programador.
/141
Excelente guionista.
/142
Gente tierna.
/143
Como un rel mpago surca por vuestra mente el recuerdo de un hechizo... de unas letras... como una antigua canci¢n olvidada de la que no pudierais recordar la m£sica ni la letra... tan solo el sentimiento de que... una vez... al pronunciar esa palabra... 
/144
fuisteis una ni¤a feliz.
/145
 la celda.
/146
l laboratorio.
/147
Os acerc is a la ventana y sent¡s el frescor de la noche envolveros. Las arenas se extienden bajo la luz de la luna, hipn¢ticas y fr¡as. Por un instante os tienta la idea de intentar saltar... pero un vistazo al abismo os llena de desesperaci¢n: la ca¡da 
/148
ser¡a mortal.
/149
Cog‚is un libro al azar. Su t¡tulo es "TO NEKPONOMIKON". La mayor parte del contenido est  en griego aunque tambi‚n hay algunas p ginas que parecen sortilegios en  rabe. Quiz s os resulte de utilidad si logr is regresar a Aval¢n. 
/150
Ahora ten‚is el Necronomic¢n.
/151
Es in£til seguir acumulando libros en lenguas que no entend‚is, con uno ya es suficiente.
/152
Encuadernado en piel algo ara¤ada y descolorida con numeros¡simos grabaditos de madera, signos y s¡mbolos m¡sticos. Parece un tratado de magia ceremonial. 
/153
Imposible entender que pone en sus p ginas. Si recordarais vuestros hechizos para interpretar lenguas extra¤as... pero parece que el nigromante ha nublado vuestra memoria y sois incapaz de recordar ninguno de los sortilegios que aprendisteis de Merl¡n 
/154
y Viviana.
/155
Durante un instante pens is en qu‚ podr¡a pasar al llegar a Aval¢n con el Necronomic¢n bajo el brazo...


Pero esa ser  otra historia...

/156
de la alfombra.
/157
con celeridad.
/158
Os sent is sobre el mullido colch¢n, pero... 
/159
Pens is en reposar sobre el blando colch¢n, pero no podr¡ais conciliar el sue¤o.
/160
No hay nada sobre lo que dormir en esta estancia.
/161
Deb‚is nombrar d¢nde os dese is sentar, princesa.
/162
Est  extendida.
/163
Os sent is sobre la alfombra, pero... 
/164
Os levant is de la alfombra.
/165
Ya est is de pie.
/166
No pod‚is sentaros sobre la alfombra 
/167
Aqu¡ no hay 
/168
ninguna alfombra.
/169
ning£n colch¢n.
/170

** LOGRO DESBLOQUEADO ** 
/171
(
/172
\/4)
/173
La mezcla de desaz¢n y pavor os impiden tener la alegr¡a requerida para entonar versos. Si acaso encontraseis la forma de recuperar, aunque fugazmente fuera, el  nimo...
/174
De lo m s profundo de vuestra alma surgen las fuerzas para no sucumbir ante el miedo. Y con ellas, el recuerdo de un poema. Una historia triste y hermosa de vuestra Breta¤a natal aunque proveniente de otro tiempo, de otro lugar... seg£n las hadas de Aval¢n 
/175
que os la ense¤aron... La recit is al son de una m£sica de vuestra propia creaci¢n.


Escucha la antigua canci¢n

de Autrou y su amad¡sima Itroun.


Dos nobles bretones lloraban

los hijos que nunca llegaban.


Un d¡a una bruja furtiva

di¢ a Autrou una respuesta cautiva.


De aquella promesa nacieron

gemelos, m s pronto exigieron


su pago: La bruja clamaba

"la vida o el lecho", gritaba.


Autrou, como buen caballero

cristiano le dijo: "No quiero


faltar a mi amada, te niego."

La bruja lo mata con fuego.


E Itroun al saber la desgracia

muri¢. Dios los tenga en su Gracia.


Os sent¡s con mayores  nimos para hacer frente a vuestro destino. Habr  alguna forma de escapar y la encontrar‚is.
/176
SIN DESBLOQUEAR.
/177
LOGROS DESBLOQUEADOS 
/178
-1: 
/179
-2: 
/180
-3: 
/181
Hab‚is dicho la palabra m gica XYZZY.
/182
Hab‚is encontrado el NECRONOMICON.
/183
Hab‚is recuperado el  nimo para CANTAR.
/184
LOGRO 1: Decir la palabra XYZZY.


La palabra m gica XYZZY fue empleada como "huevo de pascua" en la primera aventura conversacional conocida, COLOSSAL CAVE o ADVENT (Crowther - Woods, 1976). Ten¡a el efecto m gico de transportar al jugador entre distintas localidades. Ya se encontraba 
/185
LOGRO 2: Encontrar el NECRONOMICON.


El Necronomic¢n es un libro que aparece mencionado reiteradamente en los relatos del escritor H. P. Lovecraft (1890-1937) ambientados en el universo de "Los Mitos de Cthulhu". Escrito originalmente por el  rabe loco Abdul Alhazred, contendr¡a una serie de 
/186
LOGRO 3: CANTAR.


La canci¢n que Elisa de Aval¢n consigue reunir fuerzas para recitar es una creaci¢n en espa¤ol de Carlos Mart¡nez Aguirre basada en la historia narrada en el poema "La balada de Aotrou e Itroun", escrito por J. R. Tolkien en 1930. Al igual que en la pieza
/187
presente en la versi¢n preliminar de William Crowther antes de ser terminada por Don Woods, de la que se puede jugar una versi¢n en espa¤ol realizada por F‚lix Garillete y Pedro Fern ndez. 

Desde entonces su uso ha sido tradicional en las aventuras de texto, incluyendo, como no, la primera versi¢n comercial en espa¤ol de ADVENT, "La Aventura Original" (Aventuras AD, 1989)

/188
ritos arcanos para contactar con seres extradimensionales y un escaso n£mero de copias de su traducci¢n al lat¡n se conservar¡an escondidas en algunas bibliotecas y universidades del mundo.


A pesar de ser una obra enteramente ficticia todav¡a hay estudiosos e investigadores que lo buscan creyendo ingenuamente en su existencia.

/189
 tolkeniana, relata una historia caballeresca de la Breta¤a francesa medieval en forma de lay, respetando la m‚trica bretona (eneas¡labos con base de yambo y anapestos y rima consonante pareada)


/190
          
/191
­Debajo hay algo! Parece un trozo de tela...
/192
extendida sobre el suelo de la estancia.
/193
apartada, enrollada en un rinc¢n de la estancia.
/194
La alfombra ya se encuentra 
/195
Est is sentada sobre ella.
/196
No encontr is nada.
/197
Parece haber una alfombra.
/198
Despleg is la alfombra hasta que ‚sta queda extendida sobre el suelo 
/199
LOGRO 4: MIRAR el ESPEJO.


Al contemplaros en el espejo hab‚is visto el £nico gr fico del juego (aparte de la pantalla de carga). Los gr ficos han sido creados por ChatGPT, al que se ha acreditado en la presentaci¢n con el seud¢nimo de LIZZY WEIZENBAUM en homenaje a ELIZA, programa de psicoterapia por ordenador creado por Joseph Weizenbaum que fue pionero de la IA en los a¤os 60 del pasado siglo.


ChatGPT tambi‚n fue usado de un modo innovador en el argumento, mediante un peculiar "juego" que manten¡a con ‚l el autor Carlos M. Aguirre en el que ‚ste ajerc¡a de "parser" y la IA propon¡a las acciones para resolver la aventura.


Las ilustraciones de ChatGPT fueron cuidadosamente convertidas al formato de DAAD de 16 bits por Juan Jos‚ Torres y la pantalla de carga para Spectrum fue realizada manualmente por el artista Ignacio Prini.


/200
Os hab‚is mirado en el ESPEJO.
/201
-4: 
/202
¨Trozo de qu‚?
/203
El tiempo pasa... pero ello solo acerca la inevitable llegada del mago, y con ella, vuestra desdicha.
/204
 Un relieve ha llamado vuestra atenci¢n.
/205
Como objetivo adicional puedes desbloquear una serie de logros. La orden "logros" ofrecer  un listado de los logros conseguidos hasta el momento.


Los comandos "save" y "load" guardar n y recuperar n la partida en disco o cinta. A su vez "ramsave" y "ramload" servir n para guardar/cargar una £nica posici¢n del juego en la memoria del ordenador.

/206
La alfombra se fue volando...
/207
Tim Gilberts... uno di noi.
/208
Os qued is inm¢vil, conteniendo la respiraci¢n mientras trat is de afinar el o¡do. Por un momento cre‚is escuchar un eco de pasos distantes.... pero finalmente: solo hay silencio. Cada murmullo del viento contra la piedra os hace temer que el nigromante est‚ya de vuelta. El tiempo se agota, y un sudor fr¡o recorre vuestra frente mientras sent¡s que cada segundo os acerca m s hacia el terrible destino que intent is evitar a toda costa.