/OBJ
;
; Tabla de definici¢n de objetos:
; -Localidad inicial.
; -Peso.
; -Atributos de contenedor y ropa.
; -16 atributos definibles por el usuario.
; -Nombre y adjetivo.
;
/0 2 1 _ _   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  LAMPARA _
/1 0 1 _ _   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  PERGAMI _
/2 0 1 _ _   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  TELA    _
/3 0 1 _ _   _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  TROZO   _
;
